language: node_js
node_js:
  - "node"
script:
  -
deploy:
  provider: firebase
  token:
    secure: "p9luxLjCxPN0IHE0LeJNGsm7Nb5O3Dh9+keWX0SLIsjH3htWEkzfEIpNjQae7gEeMKsqyE7wxaycVlAfRWPL877gt0Dolm3mkzKzQbbtGuqoHutJ16cLlQkXr92USUwAaHiiHYDHDhgJrgtHQ5QQJmZpva3czXGT4W4WT9KsnlmsqOmBUV8F7dcpNgTHw3Bcp9NThb79Hznr5UhO1JgZyEmjONeOJ/4a3pehC56GfesC5xndSTYkXGd7RUKbG8oHGN7G1kEqE2bV1uUs4OC/PuTU+QSabxIHj33H2hheShPJ5WU5PS7swRmL5GTYN1FyB5vQ1PpVrLI/1dIjkPodnas7ng2ED+EaP1V/7t8P4kQ7t1K2RJX9ZAn1hk3X6IyRRCd3K7sYMQnIP/dOKi0r55vEleFLs7kl78mGv13KdRJEBO4zNtvx5lh827kBqfCuvLoKl9DUe7y+a/+8mOMiGE0YEnCiBg4qm4DAMwbYVucMivQVP3NLtxFn9QUcuHaqu/th/EpSWw9WCnjbNisBj9dTacGMeTWQE7vUXhFvTmQhRYf/YCTTb6kCOoO4iU8K60fHPkNdvvp4Cwk727ESkIHyiddYuC5Dwkm2gLtwlc7m1PBqzOxQUQ0Q4nVIfCOBuKRruD9rpMdKvMJS/9hmXc9sjv05kVJ2myB2UMzAMnc="